---
- name: Test Playbook
  hosts: all
  tasks:
    - name: Run Test Command
      command: hostname
      register: hostname_test

    - name: Print Hostname
      debug:
        msg: "{{ hostname_test.stdout }}"